import './globals.css'
import { Geologica } from 'next/font/google'
import Header from "../app/components/Header/Header";
import Footer from "./components/Footer/Footer";

const geologica = Geologica({ subsets: ['latin', 'cyrillic'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={geologica.className}>
        <Header />
          {children}
        <Footer />
        </body>
    </html>
  )
}
